[package]
name = "rstatus"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
sysinfo = "0.37.2"
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
